R249 B. se logra instalar jest en el motor sivel2_gen y además se logra confi…
pasosdeJesus/sivel2_gen pull request #426
Opened 2021-07-02 22:08 UTC by alejocruzrcc

…gurar coffescript para hacer pruebas a motor.
Se realiza test con una funcion y con una variable en coffeescript definido en motor.

2021-07-07 02:12 UTC, vtamara requested changes
Por favor modificar para que pruebe algo real de motro.js.coffee sin devolver versiones de nada.

2021-07-07 02:12 UTC, vtamara commented on test/dummy/package.json
> +    "@rails/webpacker": "5.4.0",
No es aceptable que devuelva webpacker a 5.4.0 cuando se ha hecho gran esfuerzo para pasarlo a 6.0.0-beta.7.

2021-07-07 02:12 UTC, vtamara commented on test/dummy/package.json
> +    "coffescript": "^0.0.1-security",
Hasta donde recuerdo es una versiń obsoleta de coffescript.

2021-07-07 02:12 UTC, vtamara commented on test/dummy/package.json
> +    "expose-loader": "^1.0.0",
Dejar expose-loader 2.0.0

2021-07-07 02:12 UTC, vtamara commented on test/dummy/package.json
> +    "webpack": "^4.46.0",
webpack en vez de devolverlo más bien subalo a 5.40.1

2021-07-07 02:12 UTC, vtamara commented on test/dummy/package.json
> +    "webpack-cli": "^3.3.12"
Adelantar en lugar de retroceder.

2021-07-07 02:12 UTC, vtamara commented on app/assets/javascripts/sivel2_gen/motor.js.coffee
> +@nombresco = () ->
Para su pruebas internas estaba bien, pero para poner en produción por favor pruebe con lo que tiene motor.js.coffee sin introducir ejemplos.

2021-07-10 11:42 UTC, vtamara requested changes

2021-07-10 11:42 UTC, vtamara commented on app/assets/javascripts/sivel2_gen/motor.js.coffee
> +module.exports = {sivel2_gen_procesa_eliminaracto: @sivel2_gen_procesa_eliminaracto, sivel2_gen_procesa_eliminaractocolectivo: @sivel2_gen_procesa_eliminaractocolectivo }
¿Cual es la consecuencia de añadir esta línea para las aplicaciones que no esperan que esto sea un módulo?

¿Podría por favor probar que por ejemplo el formulario caso y lo que tiene en javascript no se vea afectado?

2021-07-31 17:16 UTC, alejocruzrcc commented on app/assets/javascripts/sivel2_gen/motor.js.coffee
> +module.exports = {sivel2_gen_procesa_eliminaracto: @sivel2_gen_procesa_eliminaracto, sivel2_gen_procesa_eliminaractocolectivo: @sivel2_gen_procesa_eliminaractocolectivo }
lastimosamente se dañan las otras funcionalidades hechas con javascript. no se en realidad como exportar las funciones para poder invocarlas desde jest. pues en la documentación lo hacen así con module.export

2021-08-15 02:40 UTC, vtamara commented
Dado que por lo visto jest opera sólo con módulos, debería probar más bien lo del directorio app/packs.

2023-01-20 13:53 UTC, closed without merging